# Generated by Django 2.1.5 on 2020-02-26 05:16

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact number', max_length=31),
        ),
    ]
