# Generated by Django 2.1.5 on 2020-03-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0007_auto_20200321_0237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postcode',
            field=models.TextField(null=True),
        ),
    ]
