# Generated by Django 2.1.5 on 2020-03-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0008_auto_20200321_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='postcode',
        ),
    ]
