# Generated by Django 2.1.5 on 2020-03-22 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0009_remove_userprofile_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='furnished',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='n_bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, upload_to='home_images'),
        ),
        migrations.AddField(
            model_name='category',
            name='rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
