# Generated by Django 2.1.5 on 2020-03-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0010_auto_20200322_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.TextField()),
                ('address', models.TextField(default='')),
                ('n_bedrooms', models.IntegerField(default=0)),
                ('furnished', models.TextField(default='')),
                ('rent', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, upload_to='home_images/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
