# Generated by Django 2.1.5 on 2020-03-23 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp_flatswapp', '0012_auto_20200323_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='property',
            old_name='id',
            new_name='property_id',
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddField(
            model_name='user_property',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp_flatswapp.Property'),
        ),
        migrations.AddField(
            model_name='user_property',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
