# Generated by Django 2.1.5 on 2020-03-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0013_auto_20200323_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='picture',
            new_name='cover',
        ),
    ]
