# Generated by Django 2.1.5 on 2020-03-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0014_auto_20200323_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='postcode',
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
