# Generated by Django 2.1.5 on 2020-03-24 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp_flatswapp', '0015_auto_20200324_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_property',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='user_property',
            name='username',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='property',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.DeleteModel(
            name='User_Property',
        ),
    ]
