# Generated by Django 2.1.5 on 2020-03-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0016_auto_20200324_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='outdata',
            field=models.DateField(null=True),
        ),
    ]
