# Generated by Django 2.1.5 on 2020-03-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0017_property_outdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
