# Generated by Django 2.1.5 on 2020-03-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0019_auto_20200327_0047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.RemoveField(
            model_name='shortlist',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='shortlist',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shortlisted',
            field=models.ManyToManyField(related_name='shortlisted_by', to='webapp_flatswapp.Property'),
        ),
        migrations.DeleteModel(
            name='Shortlist',
        ),
    ]
