# Generated by Django 2.1.5 on 2020-03-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0021_auto_20200327_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='username',
            new_name='user',
        ),
    ]
