# Generated by Django 2.1.5 on 2020-03-27 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0026_auto_20200327_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlist',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted', to='webapp_flatswapp.Property'),
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisting', to=settings.AUTH_USER_MODEL),
        ),
    ]
