# Generated by Django 2.1.5 on 2020-03-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0028_auto_20200328_0015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shortlist',
            unique_together=set(),
        ),
    ]
