# Generated by Django 2.1.5 on 2020-03-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0029_auto_20200328_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('desciption', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='property',
            name='facility',
            field=models.ManyToManyField(null=True, to='webapp_flatswapp.Facility'),
        ),
    ]
