# Generated by Django 2.1.5 on 2020-03-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0030_propertyimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimages',
            name='prop',
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp_flatswapp.Property'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to='property_images', verbose_name='Image'),
        ),
    ]
