# Generated by Django 2.1.5 on 2020-03-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0030_auto_20200328_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='facility',
            field=models.ManyToManyField(to='webapp_flatswapp.Facility'),
        ),
    ]
