# Generated by Django 2.1.5 on 2020-03-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0031_auto_20200328_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyImages',
            new_name='Images',
        ),
    ]
