# Generated by Django 2.1.5 on 2020-03-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0031_auto_20200328_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.AddField(
            model_name='property',
            name='outcode',
            field=models.TextField(default=''),
        ),
    ]
