# Generated by Django 2.1.5 on 2020-03-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0032_auto_20200328_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='outcode',
            new_name='outward',
        ),
    ]
