# Generated by Django 2.1.5 on 2020-03-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0033_auto_20200328_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.AddField(
            model_name='property',
            name='nearest',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='neighbour',
            field=models.TextField(default=''),
        ),
    ]
