# Generated by Django 2.1.5 on 2020-03-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0034_auto_20200328_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cover',
            field=models.ImageField(blank=True, upload_to='home_images/'),
        ),
    ]
