# Generated by Django 2.1.5 on 2020-03-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0034_auto_20200328_2334'),
        ('webapp_flatswapp', '0033_auto_20200329_1239'),
    ]

    operations = [
    ]
