# Generated by Django 2.1.5 on 2020-03-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0037_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='postcode',
            new_name='address',
        ),
    ]
