# Generated by Django 2.1.5 on 2020-03-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0038_auto_20200330_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='title',
            new_name='feature',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='desciption',
        ),
    ]
