# Generated by Django 2.1.5 on 2020-03-30 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0039_auto_20200330_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='facility',
        ),
        migrations.AddField(
            model_name='facility',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp_flatswapp.Property'),
        ),
    ]
