# Generated by Django 2.1.5 on 2020-03-30 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0041_auto_20200331_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp_flatswapp.Property'),
        ),
    ]
