# Generated by Django 2.1.5 on 2020-03-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0042_auto_20200331_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='property',
        ),
        migrations.AddField(
            model_name='facility',
            name='property',
            field=models.ManyToManyField(to='webapp_flatswapp.Property'),
        ),
    ]
