# Generated by Django 2.1.5 on 2020-03-31 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0043_auto_20200331_0039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shortlist',
            unique_together={('user', 'property_id')},
        ),
    ]
