# Generated by Django 2.1.5 on 2020-03-31 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0043_auto_20200331_0039'),
        ('webapp_flatswapp', '0040_auto_20200331_0116'),
    ]

    operations = [
    ]
