# Generated by Django 2.1.5 on 2020-03-31 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0044_auto_20200331_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlist',
            old_name='property_id',
            new_name='property',
        ),
        migrations.AlterUniqueTogether(
            name='shortlist',
            unique_together={('user', 'property')},
        ),
    ]
