# Generated by Django 2.1.5 on 2020-03-31 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_flatswapp', '0045_auto_20200331_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp_flatswapp.Facility'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='feature',
            field=models.CharField(max_length=400),
        ),
    ]
